server:
  address: 0.0.0.0
  port: 10001

welcome:
  message: local dev profile for ar aimark server

spring:
  application:
    name: cn-ar-aimark-server
  #  mvc:
  #    static-path-pattern: /**
  thymeleaf:
    # 禁用模板缓存
    cache: false

  #spring 默认的json序列化, 设置时区与日期格式
  jackson:
    time-zone: GMT+8
    #date-format: yyyy-MM-dd HH:mm:ss

  #jmx远程管理
  jmx:
    enabled: true

# 远程管理
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

logging:
  config: classpath:log4j2.xml

#mybatis config
mybatis:
  config-location: classpath:mybatis-config.xml   #配置文件
  type-aliases-package: cn.ar.aimark.server.mapper  # 扫描的pojo package
  mapper-locations:           # 解析的Mapper文件路径
    - classpath:mapper/*.xml
    - classpath:mapper/auto/*.xml
    - classpath:mapper/extend/*.xml


